# Generated by Django 2.2.4 on 2019-08-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190802_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='hash_url',
            new_name='pk_hash',
        ),
    ]
